### ISSUE TITLE
synologrotated causes event & openHAB logs to get corrupted

### ISSUE THREAD

**Issue by WizBangCrash** [itn3rd77/openhab-synology-spk#6]
Hi,
I have noticed that each night when the logrotate daemon runs the event and openhab log files get corrupted and become unreadable in VSCode.
A series of "nuls" (0x00) characters get put into the log (see example here: https://www.dropbox.com/s/0pxbff6s9ak8h3f/openhab.log?dl=0).

To resolve it I have to stop openHAB, edit the log file and remove the nuls, then restart openHAB.

I cannot find any documentation for synologrotated on the web or on my Synology server, so cannot offer a suggestion for the fix at the moment, but will keep looking.

**Comment by WizBangCrash** [comment]
Hi,
I found this article describing the problem I am seeing this evening: https://superuser.com/questions/836813/remove-leading-null-blocks-from-a-sparse-file

Looks like "copytruncate" does not work well with openHAB as the openHAB logger does not recognise the truncation and is seeking to the old place in the file causing the beginning of the new file to be filled with nulls!

I've made an edit to my copy of openHAB log rotated conf to try out a suggestion I found the web:
`
/var/packages/openHAB/target/src/userdata/logs/*.log {
    daily
    rotate 7
    missingok
    dateext
    compress
    postrotate
        /usr/syno/sbin/synoservice --reload pkgctl-openHAB
    endscript
}
`
I'll let you know tomorrow i fit works.

**Comment by itn3rd77** [comment]
Hi,

I would have expected  ```--restart```. Not sure how ```--reload```  even effects openHAB.
Really interested in your results.

If that doesn't work. The only save method for sure is to overwrite the default logback configuration and roll out our own.

**Comment by WizBangCrash** [comment]
HI,
`--reload` had no effect. The logs got rotated and openHAB stopped logging anything.

Having done some more searching this morning I discovered that there is a log rotate mechanism already built into openHAB. It's in `org.ops4j.pax.logging.cfg`

On my server I have removed the `/usr/local/etc/logrotate.d/openHAB` file and added the following changes to `.../target/src/userdata/etc/org.ops4j.pax.logging.cfg`:

```
log4j2.appender.out.policies.size.size = 4MB
log4j2.appender.out.maxBackupIndex=10

log4j2.appender.event.policies.size.size = 4MB
log4j2.appender.event.maxBackupIndex=10
```

I haven't looked at what changes the installer will need to make, but I'll let you know if this rotation method works.
I would prefer to rotate on a daily basis, so need to look into the openHAB source to find out if this is possible as I couldn't find any posts in the community.
Wow. openHAB has a _really_ steep learning curve with so little documentation around!

**Comment by itn3rd77** [comment]
If you have time to test and fiddle around have a look https://logging.apache.org/log4j/log4j-2.4/manual/configuration.html#Properties.  What we want is a TimeBasedTriggeringPolicy with compression of the old logs. Haven't found a resource how to configure this with properies.

**Comment by WizBangCrash** [comment]
I downloaded the source to opsj4.pax.logging and looked at how to set up the TimeBased TriggeringPolicy.
Changed my log file configuration to:
```
log4j2.appender.event.type = RollingRandomAccessFile
log4j2.appender.event.name = EVENT
log4j2.appender.event.fileName = ${openhab.logdir}/events.log
log4j2.appender.event.filePattern = ${openhab.logdir}/events.log.%d{yyyy-mm-dd}.%i
log4j2.appender.event.immediateFlush = true
log4j2.appender.event.append = true
log4j2.appender.event.layout.type = PatternLayout
log4j2.appender.event.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-26.26c] - %m%n
log4j2.appender.event.policies.type = Policies
log4j2.appender.event.policies.size.type = TimeBasedRollingPolicy
log4j2.appender.event.policies.size.size = 4MB
log4j2.appender.event.maxHistory=7
log4j2.appender.event.strategy.type = DefaultRolloverStrategy
log4j2.appender.event.strategy.max = 10
```

But on saving the changes openhab complained:
```
2018-01-23 13:18:09,738 CM Configuration Updater (Update: pid=org.ops4j.pax.logging) ERROR Unable to locate plugin type for TimeBasedRollingPolicy
2018-01-23 13:18:09,757 CM Configuration Updater (Update: pid=org.ops4j.pax.logging) ERROR Unable to locate plugin for TimeBasedRollingPolicy
```

Any ideas on whether I can actually install a plugin for TimeBasedRollingPolicy?

NOTE:
The last 2 lines:
```
log4j2.appender.event.strategy.type = DefaultRolloverStrategy
log4j2.appender.event.strategy.max = 10
```
work, so at least I now have a policy where the file will roll when the size exceeds 4MB and keep up 10 copies :-)

**Comment by itn3rd77** [comment]
Ok, now it's getting dirty :-)

No glue at the moment and I'm still struggling with the move of the logs directory to the openhab share. Plain install of the new package works but updating the package makes problems ...

**Comment by WizBangCrash** [comment]
I didn't get time to do much last night, but I did take a look at the change you made to postinst wrt adding the link to the logs directory.
Can I ask why you are moving the logs to the openHAB share and then linking them back to the target/src/userdata/logs directory?

I added the link the other way around i.e. leave the logs directory in target/src/userdata/logs and create a link in the openHAB share to them. The reason I did this is that I only wanted access to the files I did not want to change their location.
If the link is this way around and it's a symbolic link then you can actually remove the whole of the target/src/userdata directory and replace it with a backup and the link from the openHAB share just works (assuming you have enabled links across shares in DSM).

WRT to the log rotating problem. It's messy as the options are now inside the userdata/etc folder and I guess you shouldn't just override `opsj4.pax.logging` when you do an install or an upgrade as openHAB may have changed from one release to the other.
I believe that if you have multiple entries then the last entry takes effect, so you could append whatever settings you decide to add and these will overwrite whatever settings openHAB has as the defaults, but I'm sure they'll be some 'gotcha' with doing it that way.

**Comment by itn3rd77** [comment]
> Can I ask why you are moving the logs to the openHAB share and then linking them back to the target/src/userdata/logs directory?

No specific reason. It just felt natural to me this way around. This way all user accessible data physically stored in the same folder. The logfiles a even preserved if you have to uninstall the package after a failed upgrade (which should not happen, but had to do this once). If you leave to logs inside the userdate folder they are gone after package uninstall. If you do not have a strong opinion against it's maybe just a matter of taste. Or what do you think?

> WRT to the log rotating problem. It's messy as the options are now inside the userdata/etc folder and I guess you shouldn't just override opsj4.pax.logging when you do an install or an upgrade as openHAB may have changed from one release to the other.

I think I've manged to get the daily rolling working. Need to wait a bit to confirm everything works as expected. As far as I have read the file ```org.ops4j.pax.logging.cfg``` is meant for user specific editing. The are users which do have an own log defined for there Z-Wave stuff. The official openHAB update script even makes a copy of this file to preserve user modifications. But you are right. If we touch this file I have to make sure to make a diff  against the official file with every release to catch new settings.

Stay tuned I am on the way and even ironed out some bugs in the scripts I discovered ...

**Comment by WizBangCrash** [comment]
> The logfiles a even preserved if you have to uninstall the package after a failed upgrade (which should not happen, but had to do this once). If you leave to logs inside the userdate folder they are gone after package uninstall.

My view on logs is that you cannot ever rely on the historical information being available after an application update or reboot of your system and that you have to consciously save them somewhere if you want to keep them. I've been caught a few times with apps clearing logs and their rotated logs on a restart.
My vote is to remove them on an upgrade, or if you really want to be user friendly, provide an option to save & restore them across an upgrade.

> Stay tuned I am on the way and even ironed out some bugs in the scripts I discovered ...

Sounds really good 👍 
I'm still on a steep openHAB learning curve and having fun trying to make my things, items sitemaps & rules do what I need them too. I love the HomeKit integration though. It's so cool to tell Siri to "Turn on Blu-ray player" and have my TV, amp etc. switch to the right inputs. :-)
I've given up with Docker for the time being as it was too much of a distraction, but I plan to get back to it when I have some time.

**Comment by itn3rd77** [comment]
Hi,

I have uploaded new packages for the stable 2.2 branch and the current development snapshot series 2.3. Please be aware that you have to remove your symlink before updating otherwise the installation will certainly fail. When updating and starting openHAB for the first time you get exceptions like reported here https://github.com/openhab/openhab-distro/issues/636 by myself. These only come up once and only when updating. 

Log rotation works fine for me on a daily basis. Let me know if you have further suggestions.

Regards
Ingo

**Comment by WizBangCrash** [comment]
Hi Ingo,
Thanks for the update.
I upgraded my 2.2.0 install this afternoon after removing my link without any issues (except the one you have already raised) 👍 
I'm planning to move to the 2.3.0-SNAPSHOTs this weekend as there are some things it in I'd like to use, so I'll let you know if I experience any issues with the upgrade (wrt the installer).

**Comment by itn3rd77** [comment]
If everything from this issue is addressed and solved can we close it?

**Comment by WizBangCrash** [comment]
Hi Ingo,
Two days of rotated logs all look good to me. Happy for you to close the issue. Thanks.
